# Generated by Django 3.2.23 on 2024-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_outgoing_requests", "0005_alter_outgoingrequestslog_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingrequestslogconfig",
            name="reset_db_save_after",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If configured, after the config has been updated, reset the database logging after the specified number of minutes. Note: this overrides the LOG_OUTGOING_REQUESTS_RESET_DB_SAVE_AFTER environment variable.",
                null=True,
                verbose_name="Reset saving logs in database after",
            ),
        ),
    ]
