# Generated by Django 5.2.13 on 2026-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_outgoing_requests", "0006_outgoingrequestslogconfig_reset_db_save_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoingrequestslogconfig",
            name="prettify_bodies",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "When enabled, request and response bodies for supported media "
                    "formats are pretty printed and have syntax highlighting applied "
                    "to them."
                ),
                verbose_name="prettify bodies",
            ),
        ),
    ]
