[tox]
envlist =
    py{312,313}-django{52}
    py{312,313}-django{52}-celery
    ruff
    docs
skip_missing_interpreters = true

[gh-actions]
python =
    3.12: py312
    3.13: py313

[gh-actions:env]
DJANGO =
    5.2: django52

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE=testapp.settings
    PYTHONPATH={toxinidir}
extras =
    tests
deps =
  django52: Django~=5.2.0
  celery: celery
commands =
  pytest tests \
   --cov --cov-report xml:reports/coverage-{envname}.xml \
   {posargs}

[testenv:ruff]
extras = tests
skipsdist = True
commands =
    ruff check --output-format=github .
    ruff format --check

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    tests
    docs
allowlist_externals = make
commands=
    make SPHINXOPTS="-W" html
    make linkcheck
