[tox]
envlist =
    py{312,313}-django{52}
    py{312,313}-django{52}-celery
    isort
    black
    flake8
    docs
skip_missing_interpreters = true

[gh-actions]
python =
    3.12: py312
    3.13: py313

[gh-actions:env]
DJANGO =
    5.2: django52

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE=testapp.settings
    PYTHONPATH={toxinidir}
passenv =
    PGPORT
    DB_USER
    DB_HOST
    DB_PASSWORD
extras =
    tests
deps =
  django52: Django~=5.2.0
  celery: celery
commands =
  py.test tests \
   --cov --cov-report xml:reports/coverage-{envname}.xml \
   {posargs}

[testenv:isort]
extras = tests
skipsdist = True
commands = isort --check-only --diff .

[testenv:black]
extras = tests
skipsdist = True
commands = black --check log_outgoing_requests docs testapp tests setup.py

[testenv:flake8]
extras = tests
skipsdist = True
commands = flake8 .

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    db
    tests
    docs
commands=
    py.test check_sphinx.py -v \
    --tb=auto \
    {posargs}
